name: Debian-Control-File-Build-Example

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:
  
jobs:
  deb-control-file-build-with-json:
    name: Generate Debian Package with JSON Configuration File
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build Dockerfile Container & Run App in it
        uses: ./
        id: container
        with:
          config-file: 'ExampleFiles/example_control_template.json'
          deps-file: 'ExampleFiles/product_deps.txt'
          
      - name: Prints Output File Path
        run: echo "${{ steps.container.outputs.control_file_path }}"
        
      - name: Upload Generated Control File
        uses: actions/upload-artifact@v2
        with:
          name: generated-control-file-1
          path: "${{ steps.container.outputs.control_file_path }}"
          if-no-files-found: error

  deb-control-file-build-with-manual:
    name: Generate Debian Package with Manual Arguments
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build Dockerfile Container & Run App in it
        uses: ./
        id: container
        with:
          # To Add Manual Arguments to Set
          deps-file: 'ExampleFiles/product_deps.txt'
          
      - name: Prints Output File Path
        run: echo "${{ steps.container.outputs.control_file_path }}"
        
      - name: Upload Generated Control File
        uses: actions/upload-artifact@v2
        with:
          name: generated-control-file-2
          path: "${{ steps.container.outputs.control_file_path }}"
          if-no-files-found: error
